### ISSUE TITLE
Need better handling of missing partitions

### ISSUE THREAD

**Issue by madisongh** [madisongh/tegra-boot-tools#16]
Some of the partitions packed into a BUP payload are optional and may not be present on some platforms, such as BMP and EKS. `tegra-bootloader-update` is reporting errors when partitions don't exist for all of the entries in a BUP payload.

Since the BUP generator scripts hard-code all of the entries they include, we need some way to allow for some partitions to be missing.  For example, extending the configuration file that enumerates the boot device partition entries to list all of the partitions, and skipping any BUP entries for partitions not in the full list, should take care of this.

Either that, or the BUP generator could be improved to align the included partitions with the flash layout XML file, so only those partitions present get included. That would probably be harder to implement, though.

**Comment by ichergui** [comment]
Hey Matt, 
The BUP generator is based on the flash XML file. should we create a specific one for BUP generation purposes ? 
We can use a global variable which contains a list if partitions and we can apply a `sed` command to create the XML file that could be used only for BUP generation.
What do you think ?

**Comment by madisongh** [comment]
> The BUP generator is based on the flash XML file.

The contents are controlled by the shell functions in `l4t_bup_gen.func`.
