### ISSUE TITLE
nvbootctrl is-slot-bootable alternative

### ISSUE THREAD

**Issue by tjnix** [madisongh/tegra-boot-tools#24]
Hello! Is there a suggested alternative to `nvbootctrl is-slot-bootable`? This functionality isn't implemented in `nvbootctrl` or `tegra-boot-control`.

**Comment by madisongh** [comment]
Do you mean for JetPack 5/L4T R35.1.0? If so, then, no, I don't think so.

**Comment by tjnix** [comment]
I'm using Jetpack 4.4 (`dunfell-l4t-r32.4.3`).

**Comment by madisongh** [comment]
Hmm.  And `nvbootctrl` doesn't implement the `mark-slot-unbootable`  / `is-slot-bootable` commands in that release?  I've never had cause to use them, so I've never actually checked on that.

From reading the cboot sources, if the priority and retry count are zero in the SMD for a boot slot, then that slot is considered unbootable, so it shouldn't be too hard to implement.

**Comment by tjnix** [comment]
Correct.

Oh ok. I was thinking there was a special "`bootable`" variable in the SMD that had to be set or unset. If it is just dependent on the priority and retry count, I could use that for my logic.

I guess the problem would be if I wanted to implement something like `mark-slot-unbootable`, presumably I would force the retry count to zero but there is no API for doing that currently.

**Comment by tjnix** [comment]
I'm planning to use the `nvbootctrl` binary from NVidia's Jetpack instead.
