### ISSUE TITLE
Is this tool retired

### ISSUE THREAD

**Issue by x1a0b0** [madisongh/tegra-boot-tools#31]
Is this tool retired, usages in tegra-demo-distro are deleted

**Comment by dwalkes** [comment]
I don't believe they are supported after r35.  See https://github.com/OE4T/meta-tegra/commit/ecbc750da905987714bb3279c0ca2408020ee83a

**Comment by madisongh** [comment]
That said, there are still plenty of users of Jetsons that are stuck on the L4T R32.x series, so these tools still get used.  See the `kirkstone-l4t-r32.7.x` branch in the layer and demo distro repos.
